# -----------  Agents  -----------
[[agents]]
id = 'alice'
name = 'Alice'
keystore_file = 'alice.key'
public_address = 'HcSCjvRnJYGpcje6gmI7h8VQrZiCjp5p4J4dWGBeDIwu47gc36BH9uquu8W3usa'

# -----------  DNAs  -----------

[[dnas]]
  id = "basic_chat_dna"
  file = "./dna/basic-chat.dna.json"
  hash = "QmeJnLRPQVK1CRH6pKPAHiJ9nXKCasD9387KBcphcBUpoL"


# -----------  Instances  -----------

[[instances]]
  id = "basic-chat"
  dna = "basic_chat_dna"
  agent = "alice"
[instances.storage]
  type = "memory"

# -----------  Interfaces  -----------

[[interfaces]]
  id = "websocket_interface"
  admin = true
[interfaces.driver]
  type = "websocket"
  port = 3401
[[interfaces.instances]]
  id = "basic-chat"
# -----------  Networking  -----------

[network]
  type = "sim2h"
  sim2h_url = 'wss://localhost:9000'
  # sim2h_url = 'wss://sim2h.holochain.org:9000'
