# -----------  Agents  -----------
[[agents]]
id = 'bob'
name = 'Bob'
keystore_file = 'bob.key'
public_address = 'HcScJIqWBbSaamdrw8h83GJboRQct7tpaBDtfOeuTfocpynkwmJ8RAyKXrwy45r'

# -----------  DNAs  -----------

[[dnas]]
  id = "basic_chat_dna"
  file = "./dna/basic-chat.dna.json"
  hash = "QmeJnLRPQVK1CRH6pKPAHiJ9nXKCasD9387KBcphcBUpoL"


# -----------  Instances  -----------

[[instances]]
  id = "basic-chat"
  dna = "basic_chat_dna"
  agent = "bob"
[instances.storage]
  type = "memory"

# -----------  Interfaces  -----------

[[interfaces]]
  id = "websocket_interface"
  admin = true
[interfaces.driver]
  type = "websocket"
  port = 3402
[[interfaces.instances]]
  id = "basic-chat"
# -----------  Networking  -----------

[network]
  type = "sim2h"
  sim2h_url = 'wss://localhost:9000'
  # sim2h_url = 'wss://sim2h.holochain.org:9000'
